### ISSUE TITLE
Testing produce_array_config.py: config errors

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#111]
Testing produce_array_config.py on branch array-model-and-layout:

```
python applications/produce_array_config.py --label test --array_config data/test-data/arrayConfigTest.yml -v DEBUG
DEBUG::array_model(l87)::__init__::Init ArrayModel
DEBUG::layout_array(l99)::__init__::Init LayoutArray
DEBUG::telescope_data(l104)::__init__::Init TelescopeData
WARNING::layout_array(l533)::_getCrsLocal::crs_local cannot be built because center lon and lat are missing
WARNING::layout_array(l543)::_getCrsUtm::crs_utm cannot be built because center lon and lat are missing
WARNING::telescope_data(l574)::convertAll::crsLocal is None - convertions will be impacted
WARNING::telescope_data(l576)::convertAll::crsUtm is None - convertions will be impacted
WARNING::telescope_data(l601)::convertAll::CORSIKA convertions cannot be done - missing obs level and/or sphere center
ERROR::config(l84)::get::Config does not contain dataLocation
Traceback (most recent call last):
  File "applications/produce_array_config.py", line 126, in <module>
    arrayConfigFile=args.array_config
  File "/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/simtools/model/array_model.py", line 99, in __init__
    self._loadArrayData(arrayConfigData)
  File "/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/simtools/model/array_model.py", line 129, in _loadArrayData
    label=self.label
  File "/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/simtools/layout/layout_array.py", line 164, in fromLayoutArrayName
    'telescope_positions-{}.ecsv'.format(validLayoutArrayName)
  File "/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/simtools/io_handler.py", line 162, in getDataFile
    return Path(cfg.get('dataLocation')).joinpath(parentDir).joinpath(fileName)
  File "/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/simtools/config.py", line 85, in get
    raise KeyError()
KeyError
```

**Comment by RaulRPrado** [comment]
The config file key 'testDataLocation' was replaced by 'dataLocation'. You have to change it in your local config file.
(I should have mentioned that in the PR, but I forgot.)

**Comment by GernotMaier** [comment]
Correct - this works now, thanks!
