### ISSUE TITLE
Error running applications/produce_array_config.py example

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#157]
When running the example for writing configuration files
```
python applications/produce_array_config.py --label test --array_config data/test-data/arrayConfigTest.yml -v DEBUG
```

The following error appears:

```
 python applications/produce_array_config.py --label test --array_config data/test-data/arrayConfigTest.yml -v DEBUG
DEBUG::array_model(l86)::__init__::Init ArrayModel
DEBUG::layout_array(l109)::__init__::Init LayoutArray
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::general(l162)::_validateAndConvertValue::Value len of corsikaSphereCenter: 3
DEBUG::general(l162)::_validateAndConvertValue::Value len of corsikaSphereRadius: 3
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
WARNING::layout_array(l573)::_getCrsLocal::crs_local cannot be built because center lon and lat are missing
WARNING::layout_array(l583)::_getCrsUtm::crs_utm cannot be built because center lon and lat are missing
WARNING::telescope_data(l622)::convertAll::crsLocal is None - convertions will be impacted
WARNING::telescope_data(l624)::convertAll::crsUtm is None - convertions will be impacted
WARNING::telescope_data(l648)::convertAll::CORSIKA convertions cannot be done - missing obs level and/or sphere center
INFO::layout_array(l299)::readTelescopeListFile::Reading telescope list from /workdir/external/gammasim-tools/data/layout/telescope_positions-North-Prod5.ecsv
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::telescope_data(l129)::__init__::Init TelescopeData
DEBUG::general(l258)::collectDataFromYamlOrDict::configData has not been provided (by yaml file neither by dict)
DEBUG::names(l156)::validateName::Correcting name Prod5 -> 2020-06-28
DEBUG::db_handler(l66)::__init__::Initialize DatabaseHandler
maierg@warp.zeuthen.desy.de's password:
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: LST-1
DEBUG::telescope_model(l103)::__init__::Init TelescopeModel
DEBUG::telescope_model(l269)::_loadParametersFromDB::Reading telescope parameters from DB
DEBUG::db_handler(l66)::__init__::Initialize DatabaseHandler
DEBUG::db_handler(l384)::_getModelParametersMongoDB::TelNameDB: North-LST-1
DEBUG::db_handler(l385)::_getModelParametersMongoDB::TelClass: LST
DEBUG::db_handler(l463)::readMongoDB::Trying the following query: {'Telescope': 'North-LST-1', 'Version': '2020-06-28'}
DEBUG::telescope_model(l280)::_loadParametersFromDB::Reading site parameters from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: LST-1
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model LST-1 already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: LST-1
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model LST-1 already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: LST-1
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model LST-1 already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::telescope_model(l103)::__init__::Init TelescopeModel
DEBUG::telescope_model(l269)::_loadParametersFromDB::Reading telescope parameters from DB
DEBUG::db_handler(l66)::__init__::Initialize DatabaseHandler
DEBUG::db_handler(l384)::_getModelParametersMongoDB::TelNameDB: North-MST-FlashCam-D
DEBUG::db_handler(l385)::_getModelParametersMongoDB::TelClass: MST
DEBUG::db_handler(l463)::readMongoDB::Trying the following query: {'Telescope': 'North-MST-FlashCam-D', 'Version': '2020-06-28'}
DEBUG::db_handler(l463)::readMongoDB::Trying the following query: {'Telescope': 'North-MST-Structure-D', 'Version': '2020-06-28'}
DEBUG::telescope_model(l280)::_loadParametersFromDB::Reading site parameters from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l288)::_proccessSingleTelescope::Grabbing tel data as dict - name: MST-NectarCam-D, 2 pars to change
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-NectarCam-D
DEBUG::telescope_model(l103)::__init__::Init TelescopeModel
DEBUG::telescope_model(l269)::_loadParametersFromDB::Reading telescope parameters from DB
DEBUG::db_handler(l66)::__init__::Initialize DatabaseHandler
DEBUG::db_handler(l384)::_getModelParametersMongoDB::TelNameDB: North-MST-NectarCam-D
DEBUG::db_handler(l385)::_getModelParametersMongoDB::TelClass: MST
DEBUG::db_handler(l463)::readMongoDB::Trying the following query: {'Telescope': 'North-MST-NectarCam-D', 'Version': '2020-06-28'}
DEBUG::db_handler(l463)::readMongoDB::Trying the following query: {'Telescope': 'North-MST-Structure-D', 'Version': '2020-06-28'}
DEBUG::telescope_model(l280)::_loadParametersFromDB::Reading site parameters from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l207)::_buildArrayModel::TelModelName: MST-FlashCam-D
DEBUG::array_model(l227)::_buildArrayModel::Copying tel model MST-FlashCam-D already loaded from DB
DEBUG::array_model(l247)::_buildArrayModel::Changing 2 pars of a M-05: fadc_pulse_shape, ...
DEBUG::telescope_model(l413)::changeParameter::Changing parameter fadc_pulse_shape
DEBUG::telescope_model(l413)::changeParameter::Changing parameter discriminator_pulse_shape
Name: L-01	 Model: LST-1
Name: L-02	 Model: LST-1
Name: L-03	 Model: LST-1
Name: L-04	 Model: LST-1
Name: M-01	 Model: MST-FlashCam-D
Name: M-02	 Model: MST-FlashCam-D
Name: M-03	 Model: MST-FlashCam-D
Name: M-04	 Model: MST-FlashCam-D
Name: M-05	 Model: MST-NectarCam-D
Name: M-06	 Model: MST-FlashCam-D
Name: M-07	 Model: MST-FlashCam-D
Name: M-08	 Model: MST-FlashCam-D
Name: M-09	 Model: MST-FlashCam-D
Name: M-10	 Model: MST-FlashCam-D
Name: M-11	 Model: MST-FlashCam-D
Name: M-12	 Model: MST-FlashCam-D
Name: M-13	 Model: MST-FlashCam-D
Name: M-14	 Model: MST-FlashCam-D
Name: M-15	 Model: MST-FlashCam-D
DEBUG::array_model(l344)::exportSimtelTelescopeConfigFiles::Exporting config file for tel LST-1
DEBUG::db_handler(l66)::__init__::Initialize DatabaseHandler
DEBUG::db_handler(l252)::exportModelFiles::Exporting model files from MongoDB
Traceback (most recent call last):
  File "/workdir/external/gammasim-tools/applications/produce_array_config.py", line 135, in <module>
    arrayModel.exportAllSimtelConfigFiles()
  File "/workdir/external/gammasim-tools/simtools/model/array_model.py", line 391, in exportAllSimtelConfigFiles
    self.exportSimtelTelescopeConfigFiles()
  File "/workdir/external/gammasim-tools/simtools/model/array_model.py", line 345, in exportSimtelTelescopeConfigFiles
    telModel.exportConfigFile()
  File "/workdir/external/gammasim-tools/simtools/model/telescope_model.py", line 495, in exportConfigFile
    self.exportModelFiles()
  File "/workdir/external/gammasim-tools/simtools/model/telescope_model.py", line 489, in exportModelFiles
    db.exportModelFiles(parsFromDB, self._configFileDirectory)
  File "/workdir/external/gammasim-tools/simtools/db_handler.py", line 256, in exportModelFiles
    file = self._getFileMongoDB(
  File "/workdir/external/gammasim-tools/simtools/db_handler.py", line 658, in _getFileMongoDB
    raise FileNotFoundError(
FileNotFoundError: The file array_trigger_prod5_lapalma_extended.dat does not exist in the database CTA-Simulation-Model
INFO::db_handler(l180)::_closeSSHTunnel::Closing SSH tunnel(s)
```

Not sure if this is a missing file in the DB? If yes, is this the intended behaviour?

**Comment by orelgueta** [comment]
Yes, this file is missing from the DB, see #152. I am actually using these two files to develop the application to insert files to the DB. The southern one is already there, the northern one I was waiting to upload for further tests, but never mind. 

I uploaded it now, so please check again if you get this error.

**Comment by GernotMaier** [comment]
Great, works now, Thanks!
