### ISSUE TITLE
Error running applications/derive_mirror_rnda.py

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#158]
Running this application with the master branch results in :

```
python applications/derive_mirror_rnda.py --site North --telescope MST-FlashCam-D --mean_d80 1.4 --sig_d80 0.16 --mirror_list mirror_MST_focal_lengths.dat --d80_list mirror_MST_D80.dat --rnda 0.0075
maierg@warp.zeuthen.desy.de's password:
Traceback (most recent call last):
  File "/conda/envs/gammasim-tools-dev/lib/python3.9/site-packages/astropy/units/quantity.py", line 333, in __new__
    value = float(v.group())
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workdir/external/gammasim-tools/applications/derive_mirror_rnda.py", line 313, in <module>
    meanD80, sigD80 = run(rndaStart)
  File "/workdir/external/gammasim-tools/applications/derive_mirror_rnda.py", line 246, in run
    ray = RayTracing.fromKwargs(
  File "/workdir/external/gammasim-tools/simtools/ray_tracing.py", line 185, in fromKwargs
    return cls(**args, configData=configData)
  File "/workdir/external/gammasim-tools/simtools/ray_tracing.py", line 127, in __init__
    self.config = gen.validateConfigData(_configDataIn, _parameters)
  File "/workdir/external/gammasim-tools/simtools/util/general.py", line 107, in validateConfigData
    validatedValue = _validateAndConvertValue(parName, parInfo, valueData)
  File "/workdir/external/gammasim-tools/simtools/util/general.py", line 175, in _validateAndConvertValue
    if any([u.Quantity(v).unit != u.dimensionless_unscaled for v in value]):
  File "/workdir/external/gammasim-tools/simtools/util/general.py", line 175, in <listcomp>
    if any([u.Quantity(v).unit != u.dimensionless_unscaled for v in value]):
  File "/conda/envs/gammasim-tools-dev/lib/python3.9/site-packages/astropy/units/quantity.py", line 336, in __new__
    raise TypeError('Cannot parse "{}" as a {}. It does not '
TypeError: Cannot parse "all" as a Quantity. It does not start with a number.
INFO::db_handler(l180)::_closeSSHTunnel::Closing SSH tunnel(s)
```

**Comment by RaulRPrado** [comment]
Fixed by #164
