### ISSUE TITLE
Warning messages when running make html

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#218]
I am trying to run `make html` in the doc branch and get the following warnings. The might be ok, just want to post them here to make sure you are aware of it. 

```
make html
Running Sphinx v4.4.0
loading pickled environment... done
[autosummary] generating autosummary for: applications.rst, camera_efficiency.rst, databases.rst, framework.rst, getting_started.rst, guidelines.rst, index.rst, layout_array.rst, library.rst, mc_model.rst, ray_tracing.rst, simtel.rst, simulators.rst, util.rst
Failed to import production.
Possible hints:
* TypeError: numpy.dtype is not a type object
* KeyError: 'production'
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] applications
WARNING: autodoc: failed to import module 'production'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/maierg/miniconda3/envs/gammasim-tools-dev/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/Users/maierg/miniconda3/envs/gammasim-tools-dev/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/production.py", line 54, in <module>
    from simtools.array_simulator import ArraySimulator
  File "/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/simtools/array_simulator.py", line 12, in <module>
    from simtools.simtel.simtel_histograms import SimtelHistograms
  File "/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/simtools/simtel/simtel_histograms.py", line 7, in <module>
    from eventio import EventIOFile, Histograms
  File "/Users/maierg/miniconda3/envs/gammasim-tools-dev/lib/python3.7/site-packages/eventio/__init__.py", line 2, in <module>
    from . import iact
  File "/Users/maierg/miniconda3/envs/gammasim-tools-dev/lib/python3.7/site-packages/eventio/iact/__init__.py", line 7, in <module>
    from .objects import (
  File "/Users/maierg/miniconda3/envs/gammasim-tools-dev/lib/python3.7/site-packages/eventio/iact/objects.py", line 12, in <module>
    from ..tools import (
  File "/Users/maierg/miniconda3/envs/gammasim-tools-dev/lib/python3.7/site-packages/eventio/tools.py", line 3, in <module>
    from .var_int import get_length_of_varint, parse_varint
  File "eventio/var_int.pyx", line 1, in init eventio.var_int
TypeError: numpy.dtype is not a type object

/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/validate_optics.py:docstring of validate_optics:2: WARNING: duplicate label applications:summary, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/validate_optics.py:docstring of validate_optics:21: WARNING: duplicate label applications:command line arguments, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/validate_optics.py:docstring of validate_optics:40: WARNING: duplicate label applications:example, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/compare_cumulative_psf.py:docstring of compare_cumulative_psf:2: WARNING: duplicate label applications:summary, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/compare_cumulative_psf.py:docstring of compare_cumulative_psf:20: WARNING: duplicate label applications:command line arguments, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/compare_cumulative_psf.py:docstring of compare_cumulative_psf:41: WARNING: duplicate label applications:example, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/tune_psf.py:docstring of tune_psf:2: WARNING: duplicate label applications:summary, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/tune_psf.py:docstring of tune_psf:24: WARNING: duplicate label applications:command line arguments, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/tune_psf.py:docstring of tune_psf:47: WARNING: duplicate label applications:example, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/validate_camera_efficiency.py:docstring of validate_camera_efficiency:2: WARNING: duplicate label applications:summary, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/validate_camera_efficiency.py:docstring of validate_camera_efficiency:14: WARNING: duplicate label applications:command line arguments, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/validate_camera_efficiency.py:docstring of validate_camera_efficiency:25: WARNING: duplicate label applications:example, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/validate_camera_fov.py:docstring of validate_camera_fov:2: WARNING: duplicate label applications:summary, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/validate_camera_fov.py:docstring of validate_camera_fov:13: WARNING: duplicate label applications:command line arguments, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/validate_camera_fov.py:docstring of validate_camera_fov:24: WARNING: duplicate label applications:example, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/make_regular_arrays.py:docstring of make_regular_arrays:2: WARNING: duplicate label applications:summary, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/make_regular_arrays.py:docstring of make_regular_arrays:11: WARNING: duplicate label applications:command line arguments, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/make_regular_arrays.py:docstring of make_regular_arrays:16: WARNING: duplicate label applications:example, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/produce_array_config.py:docstring of produce_array_config:2: WARNING: duplicate label applications:summary, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/produce_array_config.py:docstring of produce_array_config:52: WARNING: duplicate label applications:command line arguments, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/produce_array_config.py:docstring of produce_array_config:61: WARNING: duplicate label applications:example, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/sim_showers_for_trigger_rates.py:docstring of sim_showers_for_trigger_rates:2: WARNING: duplicate label applications:summary, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/sim_showers_for_trigger_rates.py:docstring of sim_showers_for_trigger_rates:13: WARNING: duplicate label applications:command line arguments, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/sim_showers_for_trigger_rates.py:docstring of sim_showers_for_trigger_rates:36: WARNING: duplicate label applications:example, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/add_file_to_db.py:docstring of add_file_to_db:2: WARNING: duplicate label applications:summary, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/add_file_to_db.py:docstring of add_file_to_db:9: WARNING: duplicate label applications:command line arguments, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/applications/add_file_to_db.py:docstring of add_file_to_db:20: WARNING: duplicate label applications:example, other instance in /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/docs/source/applications.rst
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex py-modindex done
highlighting module code... [100%] util.names
writing additional pages... search done
copying images... [100%] images/validate_camera_fov_North-LST-1_pixelLayout.png
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 28 warnings.

The HTML pages are in build/html.

```

**Comment by RaulRPrado** [comment]
I am aware of it. The warning about duplication are harmless and I could not fix it. It is due to the fact that we use subsections with same name in all applications.

The error on the production application is more serious. It seems to come from the eventio. I will do some tests to understand it better.
