### ISSUE TITLE
plot_array.py: missing config.yml

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#67]
This look like a set up issue, but my feeling is that the error is not really caught correctly.

```
 python applications/plot_array.py -l telescope_positions_prod5hyper_south.ecsv -s CTA.prod5S.BL-0LSTs25MSTs50SSTs-MSTN.lis
Traceback (most recent call last):
  File "applications/plot_array.py", line 36, in <module>
    outputDir = io.getApplicationOutputDirectory(cfg.get('outputLocation'), label)
  File "/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/simtools/config.py", line 76, in get
    config = loadConfig()
  File "/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim/gammasim-tools/simtools/config.py", line 52, in loadConfig
    with open(thisFileName, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yml'
``

**Comment by GernotMaier** [comment]
Solved - for above application this is enough:

```
cp config_template.yml config.yml
```
